Main svc
DavidovichIvan/java-explore-with-me pull request #5
Opened 2023-09-24 10:12 UTC by DavidovichIvan

2023-09-24 18:18 UTC, EugeneLenkevich commented
> Добрый день! Я в некотором шоке, что дошел до этой точки) Объем работы громадный мне показался (по крайней мере пока не сделана была большая часть). Пришлось отпуск брать незапланированный ).

Ну это на самом деле тот еще марафон :)

> По самому коду - старался делать всё настолько просто, насколько я могу и понимаю.  Удивительно, но почти что весь функционал взяли на себя JPA репозитории, мне даже почти Query не пришлось писать. По сути всё свелось больше к архитектуре что-ли чем к коду, ну видимо для этого и придумали все спрингбуты и гибернейты. Сваггер дал кучу схем для ДТО классов, я бы наверное столько не делал. Но с другой стороны в чем-то проще по шаблону работать.

А это на самом деле очень даже разумный подход, вообще, чем код проще - тем его проще потом поддерживать  
Ну и да, основной смысл всех этих фреймворков в том чтобы экономить время разработки :) 

> В целом испытываю смешанные чувства от проделанной работы).

Тут главное не удариться в перфекционизм, решение может и не оптимальное в каких то моментах, но оно же рабочее, все тесты проходит, а это означает что с ним все в порядке, оно свою функцию выполняет :)

2023-09-24 18:37 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Отличная работа! :)

Пара буквально моментов - хотелось бы избавиться от try-catch, кажется что могут затруднять понимание кода, ну и проверь, пожалуйста, чтобы equals и hashCode сущностей считались по неизменяемым полям, часто делают просто по id :)

2023-09-24 18:37 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminCategory/AdminCategoryService.java
> +        } catch (DataIntegrityViolationException e) {
Тут возможно можно обойтись без try-catch и делать дополнительный запрос на проверку существования подобной записи через метод репозитория, что то вроде existByName, который вернет true или false. Красивее и нагляднее будет выглядеть, а иначе придется гадать почему исключение упало. И, кстати, а вдруг ошибка упадет по другой причине, в процессе эксплуатации повесили ограничение на какое то другое поле, а тут поправить забыли :)

2023-09-24 18:37 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminCategory/AdminCategoryService.java
> +        } catch (DataIntegrityViolationException e) {
Вот тут тоже бы отдельную проверочку на существование отдельным запросом, а то получается несколько неочевидно, метод флуш репозитория(вообще технические детали реализации) слабо связан по смыслу с бизнес-логикой проверки корректности данных :)

2023-09-24 18:37 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminUser/AdminUserService.java
> +    private final int maxEmailLength = 254;
Если хочется сделать круче, то можно засунуть эти параметры в файл настроек

https://www.tutorialspoint.com/spring_boot/spring_boot_application_properties.htm

![image](https://github.com/DavidovichIvan/java-explore-with-me/assets/109306643/26297fa7-4277-4b16-a645-89938b94e661)

![image](https://github.com/DavidovichIvan/java-explore-with-me/assets/109306643/be1dbb3e-ee68-49c1-8595-b1344c59935c)

2023-09-24 18:37 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private String name;
@EqualsAndHashCode.Include
 private String name;

Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа) :)

2023-09-24 18:37 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationDto/NewCompilationDto.java
> +    @Value("false")
@Value("false")

Есть ощущение , что значение этой проперти будет всегда false, может в настройку вынести? :)

2023-09-25 08:06 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationDto/NewCompilationDto.java
> +    @Value("false")
Вообще убрал, избыточно по-сути.

2023-09-25 08:08 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private String name;
Ну да, понял, пробежался по сущностям, в 2х классах убрал лишнее.

2023-09-25 12:10 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminCategory/AdminCategoryService.java
> +        } catch (DataIntegrityViolationException e) {
Да, в этой части криво получилось, это поначалу я так пошел в админАпи, потом перестал так делать. Тут вместо того чтобы контролируемую обработку из сервиса сделать получилось как бы что снизу ждем ошибку из БД. 

Прошелся по сервисам, поправил вроде везде.

2023-09-25 12:12 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminCategory/AdminCategoryService.java
> +        } catch (DataIntegrityViolationException e) {
Переделал в нескольких местах.

2023-09-25 15:04 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminUser/AdminUserService.java
> +    private final int maxEmailLength = 254;
Спасибо, сделал в 2х классах (в AdminEventService не final и в AdminUserService final с конструктором).

2023-09-25 16:23 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminEvent/AdminEventService.java
> +    @Value("${minEventTitleLength}") //через app.prop если не final, то можно без конструктора
Да, все верно, и не надо их final делать, куча строк в конструкторе получится

2023-09-25 16:23 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminUser/AdminUserService.java
> +    private final int maxEmailLength = 254;
Вроде прикольно в итоге получилось :)

2023-09-25 16:26 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-25 16:49 UTC, merged