Feature comments
DavidovichIvan/java-explore-with-me pull request #6
Opened 2023-10-04 14:28 UTC by DavidovichIvan

2023-10-04 18:35 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста. В первую очередь лучше почистить закомментированный код, он сразу в глаза бросается :)

2023-10-04 18:35 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentController.java
> +        if (ids == null) {
Что то подсказывает что такую проверку можно сделать через аннотацию @Size перед переменной в методе контроллера :)

2023-10-04 18:35 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentService.java
> +    //интересно, без аннотации не хотел работать метод, ругался что не может надежно удалить (reliable) без транзакции
Все верно, удаление надо проводить в транзакции, мы удаляем кучу записей за раз, нам надо обеспечить изоляцию этих изменений, чтобы они произошли как одна операция (логическая транзакция, которая включает в себя много физических транзакций - удалений конкретных записей)

https://habr.com/ru/articles/469415/

2023-10-04 18:35 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/privateApi/privateComment/PrivateCommentController.java
> +        checkCommentNotEmptyNotForbidden(text);
Это больше походит на бизнес-логику, лучше опустить в сервис. Плюс сервис может вызываться не только из этого контроллера, тогда у нас получится что поведение при комментировании будет различаться в разных местах :)

2023-10-04 18:35 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/privateApi/privateComment/PrivateCommentService.java
> +        updComment.setComment(text);
А измененную сущность комментария в БД тут случаем сохранять не надо, чет не вижу где запись сохраняется? :)

2023-10-04 18:35 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/exception/IncorrectRequestException.java
> +  //  public IncorrectRequestException() {
Закомментированный код менее читаем и понятен для других разработчиков, что может привести к ошибкам и проблемам при компиляции или выполнении программы. Поэтому рекомендуется всегда удалять закомментированный код из своего кода программы.

Ну и, скорее всего, все вокруг поменяется и он станет не актуальным, а для истории есть git :)

2023-10-04 18:41 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/publicApi/publicComment/PublicCommentService.java
> +public class PublicCommentService extends BaseRepository {
>> Все сделал в том же ключе, что и второй этап - разбил на 3 апи, по самому коду тоже в принципе повторы.

Ну да, все что мы тут делаем - крудошлепство, от слова CRUD (create, retrieve, update, delete), то есть безхитростно пишем чисто методы для сохранения и извлечения данных из БД :)

>> Как писать постман нас не обучали, ну на минималках в принципе несложно разобраться, хотя я посмотрел там тоже есть куда углубляться.

Вообще, так постоянно, всяких фреймворков тьма и каждом проекте они свои могут быть и приходится с ходу разбираться. Так что норм :)


>>делал такое в первый раз, в задании к диплому написано, что нужны базовые тесты = поэтому делал очень просто все;
>>сделал тесты на каждый контроллер;
>>сделал как позитивные тесты так и негативные;
>>в процессе подготовки тестов понял, что эта работа сама по себе достаточно однообразная, по сути много >> однотипных тестов для разных методов.

Все верно :)

2023-10-05 06:18 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentController.java
> +        if (ids == null) {
Я понял, что все проверки лучше в принципе утащить из контроллеров в сервисы, поэтому тут также сделал.

2023-10-05 06:25 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentController.java
> +        if (ids == null) {
Ну, такую мелочевку можно и тут сделать/продублировать, это же потом попадет в описание схемы (в сваггер)

2023-10-05 06:27 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/exception/IncorrectRequestException.java
> +  //  public IncorrectRequestException() {
Прошелся по всему проекту, поубирал избыточные и утратившие актуальность комментарии. В принципе старался за этим смотреть. Спасиб.

2023-10-05 08:31 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentController.java
> +        if (ids == null) {
Добавил @NotEmpty, по смыслу, который я закладывал, больше подходит . Ну и в сервисе тож оставил проверку.

2023-10-05 08:34 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/privateApi/privateComment/PrivateCommentController.java
> +        checkCommentNotEmptyNotForbidden(text);
Да согласен, перенес в сервис.

2023-10-05 09:07 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/privateApi/privateComment/PrivateCommentService.java
> +        updComment.setComment(text);
Эмм.. ну тут я все проверил. Запись в бд обновлялась, у меня 3 теста в постмане для этого предусмотрено и я пока контроллеры писал каждый проверял. Ну и сейчас я проверил раз 10, метод вносит изменения в бд без явной перезаписи. 
Как-то работает оно видимо через Entity взаимосвязь автоматом срабатывает иных объяснений у меня нет.
Я видимо когда код писал забыл просто сохранение добавить, а метод отрабатывал как надо.

Добавил явное пересохранение объекта.

2023-10-05 09:14 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/publicApi/publicComment/PublicCommentService.java
> +public class PublicCommentService extends BaseRepository {
Ну да задумка была с BaseRepository чтобы не разносить явно нужные бины (в основном для собственного удобства), в отличие от того как это было в предыдущих ТЗ.

Переименовал в BaseService.

2023-10-05 09:18 UTC, DavidovichIvan commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentService.java
> +    //интересно, без аннотации не хотел работать метод, ругался что не может надежно удалить (reliable) без транзакции
Почитал статью, спасибо, была информация на эти темы в лекциях, но далеко не все запомнить удалось пока что.

2023-10-05 09:59 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/privateApi/privateComment/PrivateCommentService.java
> +        updComment.setComment(text);
Ага, оказывается так и есть, по завершении транзакции все изменения сохраняются в БД

Вот какой интересный момент (ох уж эта магия)

![image](https://github.com/DavidovichIvan/java-explore-with-me/assets/109306643/fd2c4b6b-9fb2-4877-93b4-f86de752ad36)


https://stackoverflow.com/questions/61460187/transactional-spring-jpa-save-not-necessary

2023-10-05 16:05 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/apiAndRepo/adminApi/adminComment/AdminCommentService.java
> +    //интересно, без аннотации не хотел работать метод, ругался что не может надежно удалить (reliable) без транзакции
Ну, транзакции в целом не самая простая тема

2023-10-05 16:07 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-10-05 16:47 UTC, merged